extends RefCounted
## Authored chapter data. Coordinates are local to each 46 m puzzle bay.
const IDS := ["workshop", "laundry", "thread_vault", "clocktower"]
const CHECKPOINTS := ["room_1", "room_2", "room_3", "room_3_mid", "room_4", "room_5", "room_5_mid", "room_6", "room_6_mid"]
const TITLES := ["午夜工坊", "染洗间", "悬线库", "钟楼"]

static func control(id: String, kind: String, x: float, needs: Array = [], extra: Dictionary = {}) -> Dictionary:
	var result := {"id":id, "kind":kind, "x":x, "y":0.8, "z":-0.9, "needs":needs}
	result.merge(extra, true)
	return result

static func item(id: String, kind: String, x: float, y: float = 0.08, z: float = 0.5) -> Dictionary:
	return {"id":id, "kind":kind, "x":x, "y":y, "z":z}

static func room(title: String, objective: String, devices: Array, items: Array, goal: Array, hints: Array, extra: Dictionary = {}) -> Dictionary:
	var result := {"title":title,"objective":objective,"devices":devices,"items":items,"goal":goal,"hints":hints}
	result.merge(extra, true)
	return result

static func rooms(id: String) -> Array:
	match id:
		"workshop": return [
			room("藏在木箱之后", "找回维修通道的电力", [control("hatch","latch",16,["fuse_socket"]),control("fuse_socket","socket",12,[],{"accept":"fuse"})], [item("fuse","fuse",7.0,0.08,-.95)], ["hatch"], ["木箱后有一束微弱的蓝光。","箱子既能推，也能向后拉；保险丝可以带走。","按住互动键移开箱子，把保险丝装进蓝色插座，再打开维修闩。"], {"crate":7.0}),
			room("一根电缆，两条路", "从上层配电室接通货运通道", [control("route","selector",8,[],{"modes":3}),control("upper_latch","latch",26,[],{"y":4.0}),control("cargo","latch",36,["upper_latch","route:2"])], [], ["cargo"], ["配电旋钮连接着灯和升降台。","升降台通往上层，那里能打开回程梯；货运线路需要另一档电力。","选升降档，用下层杆呼叫货篮，登篮拉行程杆；到上层开闩，下梯后切到货运档，再开出口。"], {"upper":true,"lift":"route:1","ladder_lock":"upper_latch"}),
			room("逆行的传送带", "让货箱越过隔栅，接通出口线路", [control("belt","selector",8,[],{"modes":3}),control("cargo_plate","plate",26,[],{"mass":3.0}),control("delivery","latch",35,["cargo_caught","belt:0"])], [], ["delivery"], ["隔栅下留着货箱宽的开口，尽头有一只棘爪。","箱子要先进入皮带，棘爪会承接送到的货物；停下电机，出口才获得动力。","将箱子推到皮带上，选向右输送；箱子抵达挡扣后切回停止档，再打开出口。"], {"crate":9.5,"belt":true,"mid":"cargo_caught","machine":"cargo_catch"}),
			room("压机的牙齿", "在压机下建立稳固的检修通道", [control("power","selector",7,[],{"modes":2,"initial":1}),control("limiter","plate",23,[],{"mass":3.0}),control("service","latch",34,["press_supported"])], [], ["service"], ["压头下方的黄铜框与支撑车同宽。","断电才适合搬入支撑；接触支撑后，压头的重量由车架承受。","关闭电源，把支撑车推到黄铜框，离开工作区后复电，等压头落稳再通过。"], {"crate":15.0,"press":true,"machine":"support_press"}),
			room("双路重启", "把有限的保险丝交给主轴与应急照明", [control("socket_a","socket",10,[],{"accept":"fuse","display_name":"货篮临时电源"}),control("main_socket","socket",29,[],{"accept":"fuse","display_name":"主轴电源插座"}),control("socket_b","socket",34,[],{"accept":"fuse"}),control("junction","latch",38,["main_socket","socket_b"])], [item("fuse_a","fuse",5),item("fuse_b","fuse",27,3.28)], ["junction"], ["三条线路，却只有两枚保险丝。","货篮完成运输后，它的保险丝还能取回。","先装临时电源，乘篮取回楼上保险丝；返回地面后取回临时保险丝，将两枚分别装入主轴和照明插座。"], {"upper":true,"lift":"socket_a","mid":"socket_a","machine":"power_reuse"}),
			room("最后一车", "借助运输设备封住身后的脚步", [control("belt","selector",9,[],{"modes":3}),control("barrier","latch",28,["belt:2"]),control("chute","latch",38,["barrier"])], [], ["chute"], ["门后的影子被启动的电机惊动。","反向皮带会让追来的脚步变慢；落闸后可以安全喘息。","启动后将皮带切到反转档，奔向闸门落闩，再打开货运滑槽。"], {"chase":true,"mid":"barrier","machine":"pursuit"})
		]
		"laundry": return [
			room("被淹没的楼梯", "让淹没的维修通道重新露出", [control("inlet","selector",7,[],{"modes":2,"initial":1}),control("drain","selector",15,["inlet:0"],{"modes":2,"state_names":["排水关闭","排水开启"]}),control("outlet","latch",33,["water_low"])], [], ["outlet"], ["两只阀门之间，水尺仍高过通道。","排水需要先截断进水；阀门转动之后，水还需要时间流走。","关闭进水，开启排水，等水位低于安全刻度再穿过槽底开启出口。"], {"water":true,"machine":"drain_water"}),
			room("空槽中的木筏", "让木箱载你抵达水槽上方", [control("roof_hatch","latch",12,[],{"display_name":"浮箱通路盖板"}),control("fill","selector",18.2,[],{"modes":3,"state_names":["保持水位","灌水","排水"]}),control("high_valve","latch",28,["raft_high","roof_hatch"],{"y":4.0})], [], ["high_valve"], ["木箱上方有盖板，右侧高台留下了水痕。","先让木箱对准开口，再灌水；放错位置可以排水重新布置。","推箱到水槽内的开口下，打开盖板，灌水后跳上木箱，随水升起并跳到右侧高台开阀。"], {"crate":16.0,"upper":true,"water":true,"machine":"floating_raft"}),
			room("连通的两座水箱", "用同一份水连接两边的高处通路", [control("transfer","selector",8,[],{"modes":3,"state_names":["关闭转水","转入左槽","转入右槽"]}),control("left_valve","latch",24,["left_high"],{"y":4.0}),control("upper_transfer","selector",27,["left_valve"],{"y":4.0,"modes":2,"display_name":"连廊转水阀","state_names":["保持左槽","转入右槽"]}),control("right_valve","latch",36,["left_valve","right_high"],{"y":4.0})], [], ["right_valve"], ["两根水尺互相连接，中央是干燥的连廊。","左边升起时右边下降；上层阀门可以把水送向另一侧。","将水转入左槽，乘左浮台上连廊开闩；打开连廊转水阀，等右浮台升起，再走到右端开阀。"], {"water":true,"upper":true,"mid":"left_valve","machine":"twin_water"}),
			room("失落的阀轮", "把遗失的阀轮运回机房", [control("basket","selector",8,[],{"modes":2}),control("call_lower","selector",17,["basket:1"],{"modes":2,"display_name":"下层货篮呼叫","state_names":["待命","呼叫"]}),control("call_upper","selector",25,["basket:1"],{"modes":2,"y":4.0,"display_name":"上层货篮呼叫","state_names":["待命","呼叫"]}),control("valve_socket","socket",34,[],{"accept":"wheel"}),control("return","latch",38,["valve_socket"])], [item("wheel","wheel",29,3.28)], ["return"], ["货篮两端都有呼叫杆，停靠后不会自行离开。","站在篮内也能拉动停靠杆，重物可以跟随货篮返回。","启动货篮，在篮内拉动行程杆上楼；取轮后呼叫货篮，携轮乘篮下楼，再安装出口阀。"], {"upper":true,"lift":"basket:1","machine":"callable_cargo"}),
			room("压力旁路", "让水压推动密封闸门", [control("bypass","socket",10,[],{"accept":"wheel"}),control("pressure","selector",12.3,["bypass"],{"modes":3,"state_names":["停止供水","蓄水排气","向门供压"]}),control("vent","latch",27,["water_high"],{"y":4.0}),control("pressure_upper","selector",25,["vent"],{"modes":3,"y":4.0,"linked_to":"pressure","display_name":"上层压力联动杆","state_names":["停止供水","蓄水排气","向门供压"]}),control("seal","latch",38,["hydraulic_ready"])], [item("wheel","wheel",5)], ["seal"], ["水尺升高了，门旁的压力表却没有响应。","困住的空气需要从高处排出，水位差才会推动门的活塞。","装轮并选蓄水档，乘浮台上楼排气；在上层用联动杆切到供压档，等活塞推出后下梯打开密封门。"], {"upper":true,"water":true,"mid":"vent","machine":"hydraulic_head"}),
			room("蒸汽的呼吸", "让水轮与蒸汽错开节拍", [control("wheel_drive","socket",9,[],{"accept":"gear"}),control("timing","selector",17,["wheel_drive"],{"modes":3}),control("steam_lock","latch",36,["timing:2"])], [item("gear","gear",5)], ["steam_lock"], ["蒸汽喷口会在安静与喷发之间交替。","水轮的第二档会让三组喷口依次休息。","装齿轮、选第二档，在每块安全踏板等待下一组蒸汽关闭后前进。"], {"hazards":"steam","mid":"timing:2"})
		]
		"thread_vault": return [
			room("两个砝码", "让配重货篮对上高处的停靠线", [control("tray_a","socket",10,[],{"accept":"weight"}),control("tray_b","socket",14,[],{"accept":"weight"}),control("landing","latch",28,["weight_high"],{"y":4.0})], [item("weight_a","weight",5),item("weight_b","weight",19)], ["landing"], ["货篮旁有两条停靠刻度，绳子连着两个配重盘。","每一枚砝码都会改变货篮的平衡高度。","装入两枚砝码；用呼叫杆将货篮降回底层，登篮后再松开制动升到上层开闩。"], {"upper":true,"lift":"tray_a&tray_b","machine":"weight_lift"}),
			room("上下托盘", "交换重量，接通两座相反升降的平台", [control("lower","socket",10,[],{"accept":"weight"}),control("stop","latch",23,["exchange_left"],{"y":2.3,"display_name":"中岛承重插销"}),control("upper","socket",25,["stop"],{"accept":"weight","y":2.3}),control("exchange_exit","latch",36,["exchange_right"],{"y":4.0})], [item("weight","weight",5)], ["exchange_exit"], ["两座平台的绳路分别通向两只托盘。","中岛可以固定左平台，再把同一枚砝码带给右平台。","装左盘后登上左台，在中岛锁住左台；返回取砝码，沿锁住的平台送到右盘，再乘右台到出口。"], {"upper":true,"machine":"weight_exchange"}),
			room("插销与回路", "让桥面在取走配重后仍能承重", [control("tray","socket",9,[],{"accept":"weight"}),control("pin","latch",27,["bridge_supported"],{"y":4.0}),control("reuse","socket",36,["pin"],{"accept":"weight"})], [item("weight","weight",5)], ["reuse"], ["绳子能抬桥，旁边的插销能承担重量。","桥还没有锁住时，取回砝码会让它下降。","装配重，乘篮到上层插销，下梯取回配重，观察桥仍固定，再把它送到出口托盘。"], {"upper":true,"lift":"tray","ladder_lock":"pin","mid":"pin","machine":"pinned_bridge"}),
			room("深井货运", "让砝码和你分别通过货井与窄梯", [control("hoist","selector",8,[],{"modes":2}),control("receiver","socket",28,[],{"accept":"weight","y":4.0}),control("shaft_gate","latch",38,["receiver"])], [item("weight","weight",5)], ["shaft_gate"], ["货井有防护栏，旁边窄梯只容得下空手的你。","把砝码放在货篮里，货物可以自己上楼。","将砝码放到低处货篮，开启绞盘；空手爬梯到上层，取出货物装入托盘，再下梯开门。"], {"upper":true,"lift":"hoist:1","ladder_open":true,"machine":"freight_shaft"}),
			room("铃声的另一侧", "利用声音与遮挡绕过守卫", [control("bell","bell",9,[],{"display_name":"牵引铃"}),control("hoist","selector",16,[],{"modes":2}),control("quiet_gate","latch",28,["hoist:1"],{"y":4.0})], [], ["quiet_gate"], ["守卫会转向铃声，但不会永远停留。","遮挡后的停靠点可以等待，铃声也能再次响起。","先启动货篮，再返回敲铃；趁守卫调查声源，经遮挡到货篮上楼，在上层关闩。"], {"upper":true,"lift":"hoist:1","chase":true,"mid":"bell","machine":"bell_decoy"}),
			room("三段悬桥", "用一枚砝码固定三段悬桥", [control("winch_a","socket",9,[],{"accept":"weight"}),control("pin_a","latch",18,["span_a_ready"]),control("winch_b","socket",22,["pin_a"],{"accept":"weight"}),control("pin_b","latch",28,["span_b_ready"]),control("winch_c","socket",30,["pin_b"],{"accept":"weight","display_name":"第三段配重座"}),control("pin_c","latch",37,["span_c_ready"],{"display_name":"第三段桥插销"}),control("far_latch","latch",39,["pin_a","pin_b","pin_c"])], [item("weight","weight",5)], ["far_latch"], ["三段桥各有自己的插销，只有一枚配重。","每段固定后，重量就可以交给下一段。","装左配重并固定第一段，取回后装中配重并固定第二段，再取回装第三配重、固定第三段，最后开门。"], {"bridges":true,"mid":"pin_a","machine":"three_spans"})
		]
		"clocktower": return [
			room("缺齿的传动", "让传动齿条退出门后的锁孔", [control("gear_socket","socket",10,[],{"accept":"gear"}),control("direction","selector",18,["gear_socket"],{"modes":3}),control("gear_door","latch",35,["rack_open"])], [item("gear","gear",5)], ["gear_door"], ["缺口两边的齿轮方向相反，齿条上有退出箭头。","有动力还不够，齿条需要向远离锁孔的方向移动。","装入齿轮，选择反向传动，观察齿条退出后打开主轴门。"], {"machine":"rack_drive"}),
			room("离合器", "固定货台，再把动力交给出口机构", [control("clutch","selector",8,[],{"modes":3}),control("shortcut","latch",28,["cargo_at_top"],{"y":4.0}),control("pendulum_gate","latch",38,["shortcut","clutch:2"])], [], ["pendulum_gate"], ["离合器只能带动一条轴，货台边留着停靠插销。","先让插销承重，转走动力后货台仍会保持高度。","第一档乘台到上层固定停靠插销，下梯后改用第二档驱动出口。"], {"upper":true,"lift":"clutch:1","machine":"clutch_stop"}),
			room("摆锤之间", "为两组摆锤找到安全相位", [control("brake_a","brake",12),control("brake_b","brake",25,["brake_a"]),control("phase_gate","latch",38,["brake_b"])], [], ["phase_gate"], ["制动会留住摆锤当前的位置，黄灯会预告它即将接近。","两组摆锤之间有不会被扫到的停靠点。","等第一组摆锤离开通道、青灯亮起再制动，穿到中岛；同样在第二组安全时制动并通过。"], {"hazards":"pendulum","mid":"brake_a"}),
			room("快轴与慢轴", "让两根轴的记号重合", [control("lift_power","socket",9,[],{"accept":"gear","display_name":"快轴齿轮座"}),control("slow_axis","socket",16,[],{"accept":"gear"}),control("sync_brake","brake",25,[],{"display_name":"快轴制动杆"}),control("fast_axis","latch",29,["lift_power","slow_axis","shafts_aligned"],{"display_name":"同步离合闩"})], [item("gear_a","gear",5),item("gear_b","gear",19)], ["fast_axis"], ["两根指针经过相同的刻线，速度却不同。","制动杆只停住快轴，慢轴会继续追上来。","装好两枚齿轮，等待快轴领先后制动；两根指针对齐时接合同步离合。"], {"machine":"shaft_sync"}),
			room("钟面上的记号", "让钟面记号停在释放臂前", [control("counterweight","socket",10,[],{"accept":"weight"}),control("phase","selector",18,["counterweight"],{"modes":4,"state_names":["刻度 0","刻度 I","刻度 II","刻度 III"]}),control("clock_brake","brake",26,["counterweight"]),control("hammer","latch",28,["clock_brake","phase:3","clock_aligned"])], [item("weight","weight",5)], ["hammer"], ["选择刻度会移动标记，指针仍在转动。","钟锤释放臂对应第三刻度；制动要留住真正重合的瞬间。","安装配重并选第三刻度，等指针进入高亮标记区后制动，在指针停稳时拉下钟锤闩。"], {"mid":"phase:3","machine":"clock_alignment"}),
			room("晨光之前", "敲响最后一口钟，奔向晨光", [control("release","latch",9),control("brake_a","brake",19,["release"]),control("brake_b","brake",29,["release"]),control("sunrise","latch",39,["release","brake_b"])], [], ["sunrise"], ["钟响后，整座塔都会重新运转。","安全岛可以躲开摆锤；途中仍有制动杆。","释放钟锤，分别等摆锤离开通道、青灯亮起再制动，逐段抵达最右侧晨光出口。"], {"hazards":"pendulum","mid":"release"})
		]
	return []
